### ISSUE TITLE
Running into VNC error 

### ISSUE THREAD

**Issue by leachy14** [openai/universe-windows-envs#3]
This is the error I keep running into whenever running the python code to connect from my ML computer to my GTA 5 Instance.

```
paperspace@pswaujdr:~/dev$ python maingta.py
[2017-01-11 21:50:23,485] Making new env: gtav.SaneDriving-v0
[2017-01-11 21:50:23,489] Writing logs to file: /tmp/universe-14924.log
[2017-01-11 21:50:23,490] Using the golang VNC implementation
[2017-01-11 21:50:23,490] Using VNCSession arguments: {'subsample_level': 2, 'start_timeout': 7, 'fine_quality_level': 50, 'encoding': 'tight'}. (Customize by running "env.configure(vnc_kwargs={...})"
[2017-01-11 21:50:23,490] [0] Connecting to environment: vnc://XXX.XXX.XXX.XXX password=openai. If desired, you can manually connect a VNC viewer, such as TurboVNC. Most environments provide a convenient in-browser VNC client: http://None/viewer/?password=openai
2017/01/11 21:50:23 I0111 21:50:23.490872 14924 gymvnc.go:417] [0:XXX.XXX.XXX.XXX] opening connection to VNC server
Traceback (most recent call last):
  File "maingta.py", line 14, in <module>
    observation_n, reward_n, done_n, info = env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 110, in step
    observation, reward, done, info = self._step(action)
  File "/home/paperspace/dev/universe/universe/wrappers/timer.py", line 20, in _step
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 110, in step
    observation, reward, done, info = self._step(action)
  File "/home/paperspace/dev/universe/universe/wrappers/render.py", line 30, in _step
    observation_n, reward_n, done_n, info_n = self.env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 110, in step
    observation, reward, done, info = self._step(action)
  File "/home/paperspace/dev/universe/universe/wrappers/throttle.py", line 51, in _step
    accum_observation_n, accum_reward_n, accum_done_n, accum_info = self._substep(action_n)
  File "/home/paperspace/dev/universe/universe/wrappers/throttle.py", line 132, in _substep
    observation_n, reward_n, done_n, info = self.env.step(action_n)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 110, in step
    observation, reward, done, info = self._step(action)
  File "/home/paperspace/dev/universe/universe/envs/vnc_env.py", line 440, in _step
    visual_observation_n, obs_info_n, vnc_err_n = self._step_vnc_session(action_d)
  File "/home/paperspace/dev/universe/universe/envs/vnc_env.py", line 358, in _step_vnc_session
    self.rewarder_session.send_action(compiled_d, self.spec.id)
AttributeError: 'NoneType' object has no attribute 'send_action'
```

**Comment by luiscosio** [comment]
@leachy14 Edited your comment since it contained your credentials to your AWS Instance.

**Comment by crizCraig** [comment]
hi @leachy14 - can you paste the code? also, check out this repo for an example: https://github.com/deepdrive/deepdrive-universe/blob/master/main.py

**Comment by leachy14** [comment]
You can close it! It was just an error in my main
